name: Docker and Apptainer Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
    name: Build and Push Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_CONTAINER }}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_CONTAINER }}:${{ github.run_id }}

  apptainer:
    name: Build Singularity Image File
    runs-on: ubuntu-latest
    needs: docker

    steps:
      -
        name: Set up Singularity
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.1.2
      -
        name: Build Apptainer container
        run: apptainer build ${{ secrets.DOCKER_HUB_CONTAINER }}.sif docker://${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_CONTAINER }}:latest
      -
        name: Run Apptainer container
        run: apptainer run ${{ secrets.DOCKER_HUB_CONTAINER }}.sif cat /etc/os-release
      -
        name: Upload Singularity Image File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ secrets.DOCKER_HUB_CONTAINER }}.sif
          path: ./${{ secrets.DOCKER_HUB_CONTAINER }}.sif

  release:
    name: Release Singularity Image File
    runs-on: ubuntu-latest
    needs: apptainer

    steps:
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ secrets.DOCKER_HUB_CONTAINER }}.sif
      -
        name: Test artifact download
        run: ls -R
      -
        name: Zip artifact
        uses: thedoctor0/zip-release@0.7.1
        with:
          filename: ${{ secrets.DOCKER_HUB_CONTAINER }}.zip
      - 
        name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: sif-${{ github.run_id }}
          draft: false
          prerelease: false
      - 
        name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ secrets.DOCKER_HUB_CONTAINER }}.zip
          asset_name: sif-${{ github.run_id }}.zip
          asset_content_type: application/zip
